name: ftm_service_app
description: FTM.CO Project

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  http: ^0.13.4
  page_transition: "^2.0.5"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
  assets:
    - images/ftm.png

