name: ftm_service_app
description: FTM.CO Project

publish_to: 'none'
version: 0.2.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  http: ^0.13.4
  page_transition: ^2.0.5
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.13
  persian_date: ^0.1.5
  package_info_plus: ^1.0.2
  url_launcher: ^6.0.20

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: Yekan
      fonts:
        - asset: fonts/Yekan.ttf
  assets:
    - assets/
    - assets/icon/
    - assets/images/
    - locale/fa.json
    - locale/en.json

